### ISSUE TITLE
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by Stylix58** [Stylix58/fosscord-cli#4]
For now, the CLI seen to have an issue with `bcrypt` (here is happen when using `fosscord init`):
```
npm ERR! code 1
npm ERR! path /home/natha/git/fosscord-cli/api/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/natha/git/fosscord-cli/api/node_modules/bcrypt/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/natha/.cache/node-gyp/14.17.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/natha/.cache/node-gyp/14.17.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/natha/.cache/node-gyp/14.17.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/natha/git/fosscord-cli/api/node_modules/bcrypt',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 5.8.0-59-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/natha/git/fosscord-cli/api/node_modules/bcrypt
npm ERR! gyp ERR! node -v v14.17.2
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/natha/.npm/_logs/2021-07-07T18_54_15_881Z-debug.log
child_process.js:682
    throw err;
    ^

Error: Command failed: cd api && npm i && cd ../gateway && npm i
npm ERR! code 1
npm ERR! path /home/natha/git/fosscord-cli/api/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/natha/git/fosscord-cli/api/node_modules/bcrypt/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/natha/.cache/node-gyp/14.17.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/natha/.cache/node-gyp/14.17.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/natha/.cache/node-gyp/14.17.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/natha/git/fosscord-cli/api/node_modules/bcrypt',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 5.8.0-59-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/natha/git/fosscord-cli/api/node_modules/bcrypt
npm ERR! gyp ERR! node -v v14.17.2
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/natha/.npm/_logs/2021-07-07T18_54_15_881Z-debug.log

    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at Command.init (/home/natha/git/fosscord-cli/index.js:15:5)
    at Command.listener [as _actionHandler] (/home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:466:17)
    at /home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:1170:65
    at Command._chainOrCall (/home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:1088:12)
    at Command._parseCommand (/home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:1170:27)
    at Command._dispatchSubcommand (/home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:995:25)
    at Command._parseCommand (/home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:1136:19)
    at Command.parse (/home/natha/git/fosscord-cli/node_modules/commander/lib/command.js:841:10) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(2843) [Uint8Array] [
      110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
      101,  32,  49,  10, 110, 112, 109,  32,  69,  82,  82,  33,
       32, 112,  97, 116, 104,  32,  47, 104, 111, 109, 101,  47,
      110,  97, 116, 104,  97,  47, 103, 105, 116,  47, 102, 111,
      115, 115,  99, 111, 114, 100,  45,  99, 108, 105,  47,  97,
      112, 105,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117,
      108, 101, 115,  47,  98,  99, 114, 121, 112, 116,  10, 110,
      112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 109, 109,
       97, 110, 100,  32,
      ... 2743 more items
    ]
  ],
  pid: 34035,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(2843) [Uint8Array] [
    110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
    101,  32,  49,  10, 110, 112, 109,  32,  69,  82,  82,  33,
     32, 112,  97, 116, 104,  32,  47, 104, 111, 109, 101,  47,
    110,  97, 116, 104,  97,  47, 103, 105, 116,  47, 102, 111,
    115, 115,  99, 111, 114, 100,  45,  99, 108, 105,  47,  97,
    112, 105,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117,
    108, 101, 115,  47,  98,  99, 114, 121, 112, 116,  10, 110,
    112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 109, 109,
     97, 110, 100,  32,
    ... 2743 more items
  ]
}
```

The workaround is for now to [install Yarn](https://yarnpkg.com/getting-started/install) and do `yarn add bcrypt` in `api`, `gateway` and, if its exists, `cdn`.

**Comment by Intevel** [comment]
I am closing the issue for now, if the bug persists the issue can be reopened.
